language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

# command to prepare the system to install prerequisites or dependencies
before_install:
 - sudo apt-get install -qq python-setuptools
 - sudo apt-get install -qq python-pip python-dev libshout3-dev python-liblo python-mutagen python-pycurl liblo-dev libshout3-dev librtmp-dev python-yaml libcurl4-openssl-dev python-mutagen

# command to run tests
script:
 - "python setup.py install"
# - "python tests/testcomponent.py"
